services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: realestate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/realestate_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/uploads
    restart: always

volumes:
  postgres_data:
  uploads_data:


