spring.application.name=thuba

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JWT
jwt.secret=${JWT_SECRET}

# Let Render dictate the port, default to 10000

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none


spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.user=${SPRING_DATASOURCE_USERNAME}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.url=${SPRING_DATASOURCE_URL}

# Multi-part
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB